stages:
  download_data:
    cmd: python src/download_data.py data/src/
    deps:
      - src/download_data.py
    outs:
      - data/src
  train:
    cmd: python src/train.py 
      --input-dir data/src/
      --output-dir data/model/
    params:
      - train
    deps:
      - src/train.py
      - src/models/
      - data/src/
    outs:
      - data/model/best.pt
  test:
    cmd: python src/test.py 
      --model-file data/model/best.pt
      --data-dir data/src/
      --metrics-file metrics.json
    params:
      - train
    deps:
      - src/test.py
      - src/models/
      - data/model/best.pt
      - data/src/
    metrics:
      - metrics.json:
          cache: false