stages:
  download_data:
    cmd: python src/download_data.py data/src/
    deps:
      - src/download_data.py
    outs:
      - data/src
  train:
    cmd: python src/train.py 
      --input-dir data/src/
      --output-dir data/model/
    params:
      - train
    deps:
      - src/train.py
      - data/src/
    outs:
      - data/model/best.pt